### ISSUE TITLE
SDR to Home Assistant Radio losing connection

### ISSUE THREAD

**Issue by BigBill2000** [thejeffreystone/hassio_addons#35]
Have been running just over a month now and constantly loosing connection. It happens at almost the exact same interval, last times were 2 days, 2 hours, 12 minutes and 2 days, 2 hours, 20 minutes. Very strange it is almost a pattern. Will see if it follows this 2 days from now. Running HA Blue, all latest. Tried 2 different USB ports on HA, but same. Tuner is Rafael Micro R820T tuner, I am running 433.92 and 915 with switching every 130 seconds. Thanks.
Error log=
Tuned to 433.920MHZ.
Tuned to 915.000MHz.
Tuned to 433.920MHZ.
LIBUSB_ERROR_NOT_FOUND:
Entity not found!
Check your RTL_SDR dongle,
USB cables, and power supply.
Tuned to 915.000MHz.
WARNING: async read failed
(-5).
Library error -5, exiting...

**Comment by BigBill2000** [comment]
![2022-08-12 16_40_23-History – Home Assistant](https://user-images.githubusercontent.com/40277685/184448447-78987d63-f295-4641-bc65-d231d1da2689.jpg)

**Comment by mattlward** [comment]
I am dealing with the same log messages.  Started with the HA updates this month.

**Comment by mattlward** [comment]
![image](https://user-images.githubusercontent.com/8540074/187002376-ae544d62-a949-41d8-82c4-9fd4b2dfc26d.png)

**Comment by mattlward** [comment]
Until there is a fix... I have this automation...
```
- id: Restart_RTL-SDR_if_no_data
  alias: Restart RTL-SDR if no data
  trigger:
    - platform: state
      entity_id: sensor.acurite_porch_f
      for: "00:15:00"
    - platform: state
      entity_id: sensor.acurite_stairs_f
      for: "00:15:00"
  action:
  - service: hassio.addon_restart
    data:
      addon: d63406df_sdr2mqtt
  - service: notify.sms_matt
    data:
      message: "SDR-MQTT restarted after 15 minute inactivity!"
```
